services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${Postgres__User}
      POSTGRES_PASSWORD: ${Postgres__Password}
      POSTGRES_DB: ${Postgres__Db}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "postgres" ]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - postgres-data:/var/lib/postgresql/data

  uralhiking:
    image: uralhiking
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: UralHiking/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - static-data:/app/static

volumes:
  postgres-data:
  static-data: